### ISSUE TITLE
Error: Invalid character in name

### ISSUE THREAD

**Issue by Muhammad-Fiqri** [smmoosavi/jsx-xml#19]
![image](https://github.com/smmoosavi/jsx-xml/assets/60091975/a960b8dc-7033-4aef-a40e-35e599fdbd18)

**Comment by smmoosavi** [comment]
can you add more context? what is in RSSPage that cause the error?

**Comment by ericman314** [comment]
I'm also getting this error. I'm using React 18 with vite. I think the way JSX is transformed and used in react and vite has changed considerably since this library was last updated, and the `@jsx JSXXML` pragma appears to have no effect. Vite is transforming the jsx the "regular" way as if it is going to be rendered by react, and that generated code doesn't work with jsx-xml.

Here is my testXml.tsx (straight from the README):

```js
/** @jsx JSXXML */
import { render, JSXXML } from 'jsx-xml'

const xml = render(<test x="3">1 = {2} = 3</test>)
console.log(xml)
```

Here is where the error is thrown deep in xmlbuilder:

![image](https://github.com/user-attachments/assets/fc635e08-9075-4451-ae52-5adb7c42ce18)

Here is the object that is passed to `xmlbuilder.create`:

![image](https://github.com/user-attachments/assets/1da04398-e03f-470a-9400-09d0e9855a86)

You can see that the jsx is being transformed for use with react, and JSXXML isn't being invoked at all. 

In theory, it should be possible to make this work using a custom JSX import source. You could rename the file containing the XML with a different extension not used by vite's regular react transformer, such as .jsxml, and then add a custom plugin to the vite config:

```js
// vite.config.ts
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [
    react(),
    react({ include: ['**/*.jsxml'], jsxImportSource: 'jsx-xml' }),
    ...
  ]
})
```

Assuming that `jsx-xml` could be updated to provide these imports as described in https://esbuild.github.io/api/#jsx-import-source:

```js
import { createElement } from "your-pkg"
import { Fragment, jsx, jsxs } from "your-pkg/jsx-runtime"
import { Fragment, jsxDEV } from "your-pkg/jsx-dev-runtime"
```

OR, maybe it's much simpler than this. Perhaps `JSXXML` just needs to be updated to be able to understand the object that the JSX is being transformed into in this latest version of react/vite?

```json
{
    "type": "test",
    "key": null,
    "ref": null,
    "props": {
        "x": "3",
        "children": [
            "1 = ",
            2,
            " = 3"
        ]
    },
    "_owner": null,
    "_store": {}
}
```

**Comment by smmoosavi** [comment]
Thanks for the good declaration of the issue and hints about jsx-runtime.

I will investigate the problem this week.

**Comment by smmoosavi** [comment]
I just published a beta version that understands React JSX. check `jsx-xml@beta`
